I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script
    play music mone
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/script.rpy", line 16, in <module>
    play music mone
NameError: name 'mone' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script
    play music mone
  File "/home/sirano/Документы/V-N/vis-novel/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/home/sirano/Документы/V-N/vis-novel/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/home/sirano/Документы/V-N/vis-novel/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 123, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "/home/sirano/Документы/V-N/vis-novel/renpy/python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/home/sirano/Документы/V-N/vis-novel/renpy/python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 16, in <module>
    play music mone
NameError: name 'mone' is not defined

Linux-6.2.0-32-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.0.23051307
EHU horror 0.1
Fri Sep  8 20:17:16 2023
